version: '3.8'

services:
  web:
    build: .
    container_name: helpdesk_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - uploads_data:/app/uploads
    env_file:
      - .env
    depends_on:
      - db
    command: flask run --host=0.0.0.0 --port=8000

  #Servicio de la base de datos PostgreSQL
  db:
    image: postgres:13
    container_name: helpdesk_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#Define los volúmenes para la persistencia de datos
volumes:
  postgres_data:
  uploads_data: {}